/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewRouteImport } from './routes/new'
import { Route as SpecRouteImport } from './routes/spec'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as PPacketIdRouteImport } from './routes/p.$packetId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecRoute = SpecRouteImport.update({
  id: '/spec',
  path: '/spec',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const PPacketIdRoute = PPacketIdRouteImport.update({
  id: '/p/$packetId',
  path: '/p/$packetId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/spec': typeof SpecRoute
  '/trust': typeof TrustRoute
  '/p/$packetId': typeof PPacketIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/spec': typeof SpecRoute
  '/trust': typeof TrustRoute
  '/p/$packetId': typeof PPacketIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/spec': typeof SpecRoute
  '/trust': typeof TrustRoute
  '/p/$packetId': typeof PPacketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/new' | '/spec' | '/trust' | '/p/$packetId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/new' | '/spec' | '/trust' | '/p/$packetId'
  id: '__root__' | '/' | '/new' | '/spec' | '/trust' | '/p/$packetId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewRoute: typeof NewRoute
  SpecRoute: typeof SpecRoute
  TrustRoute: typeof TrustRoute
  PPacketIdRoute: typeof PPacketIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spec': {
      id: '/spec'
      path: '/spec'
      fullPath: '/spec'
      preLoaderRoute: typeof SpecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$packetId': {
      id: '/p/$packetId'
      path: '/p/$packetId'
      fullPath: '/p/$packetId'
      preLoaderRoute: typeof PPacketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewRoute: NewRoute,
  SpecRoute: SpecRoute,
  TrustRoute: TrustRoute,
  PPacketIdRoute: PPacketIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
